CREATE TABLE censo 
   ("ANO" NUMBER(*,0) NOT NULL ENABLE, 
	"COD_UF" CHAR(2 BYTE) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"COD_MUN" CHAR(7 BYTE) NOT NULL ENABLE, 
	"NOME_MUN" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"REGIAO" VARCHAR2(150 BYTE), 
	"COD_MESO_REG" CHAR(4 BYTE), 
	"NOME_MESO_REG" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"COD_MIC_REG" CHAR(5 BYTE) NOT NULL ENABLE, 
	"NOME_MIN_REG" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PIB" NUMBER(12,3) NOT NULL ENABLE, 
	"POPULACAO" NUMBER(*,0) NOT NULL ENABLE, 
	"PIB_PER_CAP" NUMBER(12,3) NOT NULL ENABLE);